;****************************************************************************
;  rcll_problem_production_durations.pddl
;  RoboCup Logistics League Production Problem -- Durative with costs
;
;  Created: Wed Mar 22 17:44:34 2017
;  Copyright  2017  Tim Niemueller [www.niemueller.de]
;****************************************************************************

;  This program is free software; you can redistribute it and/or modify
;  it under the terms of the GNU General Public License as published by
;  the Free Software Foundation; either version 2 of the License, or
;  (at your option) any later version.
;
;  This program is distributed in the hope that it will be useful,
;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;  GNU Library General Public License for more details.
;
;  Read the full text in the LICENSE.GPL file in the doc directory.

(define (problem rcll-production-durative-prob1)
	(:domain rcll-production-durative)

	(:objects
		R-1 R-2 - robot
		; If adding R-2 and R-3, also add robot-waiting facts below
		o1 - order
		wp1 - workpiece
		cg1 cg2 cg3 cb1 cb2 cb3 - cap-carrier
		C-BS C-CS1 C-CS2 C-DS C-RS1 C-RS2 - mps
		CYAN - team-color
	)
	 
	(:init
	 (mps-type C-BS BS)
	 (mps-type C-CS1 CS)
	 (mps-type C-CS2 CS)
	 (mps-type C-DS DS)
	 (mps-type C-RS1 RS)
	 (mps-type C-RS2 RS)
	 (location-free START INPUT)
	 (location-free C-BS INPUT)
	 (location-free C-BS OUTPUT)
	 (location-free C-CS1 INPUT)
	 (location-free C-CS1 OUTPUT)
	 (location-free C-CS2 INPUT)
	 (location-free C-CS2 OUTPUT)
	 (location-free C-DS INPUT)
	 (location-free C-DS OUTPUT)
	 (location-free C-RS1 INPUT)
	 (location-free C-RS1 OUTPUT)
	 (location-free C-RS2 INPUT)
	 (location-free C-RS2 OUTPUT)
	 (cs-can-perform C-CS1 CS_RETRIEVE)
	 (cs-can-perform C-CS2 CS_RETRIEVE)
	 (cs-free C-CS1)
	 (cs-free C-CS2)
	 ; Additional base number handling static predicates
	 (rs-sub THREE TWO ONE)
	 (rs-sub THREE ONE TWO)
	 (rs-sub THREE ZERO THREE)
	 (rs-sub TWO TWO ZERO)
	 (rs-sub TWO ONE ONE)
	 (rs-sub TWO ZERO TWO)
	 (rs-sub ONE ONE ZERO)
	 (rs-sub ONE ZERO ONE)
	 (rs-sub ZERO ZERO ZERO)
	 (rs-inc ZERO ONE)
	 (rs-inc ONE TWO)
	 (rs-inc TWO THREE)
	 (rs-filled-with C-RS1 ZERO)
	 (rs-filled-with C-RS2 ZERO)
	 (wp-base-color wp1 BASE_NONE)
	 (wp-cap-color wp1 CAP_NONE)
	 (wp-ring1-color wp1 RING_NONE)
	 (wp-ring2-color wp1 RING_NONE)
	 (wp-ring3-color wp1 RING_NONE)
	 (wp-unused wp1)
	 (robot-waiting R-1)
	 (robot-waiting R-2)
	 ;(robot-waiting R-3)
	 (mps-state C-BS IDLE)
 	 (mps-state C-CS1 IDLE)
 	 (mps-state C-CS2 IDLE)
	 (mps-state C-DS IDLE)
 	 (mps-state C-RS1 IDLE)
 	 (mps-state C-RS2 IDLE)

	 (wp-cap-color cg1 CAP_GREY)
	 (wp-cap-color cg2 CAP_GREY)
	 (wp-cap-color cg3 CAP_GREY)
	 (wp-on-shelf cg1 C-CS1 LEFT)
	 (wp-on-shelf cg2 C-CS1 MIDDLE)
	 (wp-on-shelf cg3 C-CS1 RIGHT)

	 (wp-cap-color cb1 CAP_BLACK)
	 (wp-cap-color cb2 CAP_BLACK)
	 (wp-cap-color cb3 CAP_BLACK)
	 (wp-on-shelf cb1 C-CS2 LEFT)
	 (wp-on-shelf cb2 C-CS2 MIDDLE)
	 (wp-on-shelf cb3 C-CS2 RIGHT)

	 (rs-ring-spec C-RS1 RING_GREEN ZERO)
	 (rs-ring-spec C-RS1 RING_YELLOW ZERO)
	 (rs-ring-spec C-RS2 RING_BLUE ONE)
	 (rs-ring-spec C-RS2 RING_ORANGE TWO)

	 ; C0 order
	 ; (order-complexity o1 c0)
	 ; (order-base-color o1 BASE_BLACK)
	 ; (order-cap-color o1 CAP_GREY)
	 ; (order-gate o1 GATE-1)

	 ; C1 order
	 (order-complexity o1 c1)
	 (order-base-color o1 BASE_BLACK)
	 (order-ring1-color o1 RING_GREEN)
	 (order-cap-color o1 CAP_GREY)
	 (order-gate o1 GATE-1)

	 ; C2 order
	 ; (order-complexity o1 C2)
	 ; (order-base-color o1 BASE_BLACK)
	 ; (order-ring1-color o1 RING_GREEN)
	 ; ; considerably increases planning time
	 ; ;(order-ring1-color o1 RING_ORANGE)
	 ; (order-ring2-color o1 RING_BLUE)
	 ; (order-cap-color o1 CAP_GREY)
	 ; (order-gate o1 GATE-1)
	 ; (= (order-delivery-begin o1) 0)
	 ; (= (order-delivery-end o1) 900)

	 ; C3 order
	 ; With a yellow second ring (2 additional bases required in total)
	 ; solving here takes 5 seconds, with the blue ring (3 additional
	 ; bases) it runs out of memory (that is with popf 32bit that comes
	 ; ROSPlan)
	 ; (order-complexity o1 C3)
	 ; (order-base-color o1 BASE_BLACK)
	 ; (order-ring1-color o1 RING_GREEN)
	 ; ;(order-ring2-color o1 RING_YELLOW)
	 ; (order-ring2-color o1 RING_BLUE)
	 ; (order-ring3-color o1 RING_ORANGE)
	 ; (order-cap-color o1 CAP_GREY)
	 ; (order-gate o1 GATE-1)

	 ; These values are for the static default world
	 (= (path-length C-BS INPUT C-BS OUTPUT) 9.80499)
	 (= (path-length C-BS INPUT C-CS1 INPUT) 56.2377)
	 (= (path-length C-BS INPUT C-CS1 OUTPUT) 63.8106)
	 (= (path-length C-BS INPUT C-CS2 INPUT) 50.0478)
	 (= (path-length C-BS INPUT C-CS2 OUTPUT) 39.3321)
	 (= (path-length C-BS INPUT C-DS INPUT) 39.1852)
	 (= (path-length C-BS INPUT C-DS OUTPUT) 27.5249)
	 (= (path-length C-BS INPUT C-RS1 INPUT) 19.127)
	 (= (path-length C-BS INPUT C-RS1 OUTPUT) 30.0413)
	 (= (path-length C-BS INPUT C-RS2 INPUT) 21.2672)
	 (= (path-length C-BS INPUT C-RS2 OUTPUT) 11.5575)
	 (= (path-length C-BS INPUT START INPUT) 7.3014)
	 (= (path-length C-BS OUTPUT C-BS INPUT) 9.80499)
	 (= (path-length C-BS OUTPUT C-CS1 INPUT) 61.5629)
	 (= (path-length C-BS OUTPUT C-CS1 OUTPUT) 69.1358)
	 (= (path-length C-BS OUTPUT C-CS2 INPUT) 55.373)
	 (= (path-length C-BS OUTPUT C-CS2 OUTPUT) 44.6572)
	 (= (path-length C-BS OUTPUT C-DS INPUT) 44.5104)
	 (= (path-length C-BS OUTPUT C-DS OUTPUT) 34.9196)
	 (= (path-length C-BS OUTPUT C-RS1 INPUT) 24.4522)
	 (= (path-length C-BS OUTPUT C-RS1 OUTPUT) 35.3664)
	 (= (path-length C-BS OUTPUT C-RS2 INPUT) 28.662)
	 (= (path-length C-BS OUTPUT C-RS2 OUTPUT) 15.5836)
	 (= (path-length C-BS OUTPUT START INPUT) 12.2342)
	 (= (path-length C-CS1 INPUT C-BS INPUT) 56.2377)
	 (= (path-length C-CS1 INPUT C-BS OUTPUT) 61.5629)
	 (= (path-length C-CS1 INPUT C-CS1 OUTPUT) 12.9856)
	 (= (path-length C-CS1 INPUT C-CS2 INPUT) 21.4872)
	 (= (path-length C-CS1 INPUT C-CS2 OUTPUT) 20.915)
	 (= (path-length C-CS1 INPUT C-DS INPUT) 26.9309)
	 (= (path-length C-CS1 INPUT C-DS OUTPUT) 35.1973)
	 (= (path-length C-CS1 INPUT C-RS1 INPUT) 41.8211)
	 (= (path-length C-CS1 INPUT C-RS1 OUTPUT) 31.2251)
	 (= (path-length C-CS1 INPUT C-RS2 INPUT) 47.0858)
	 (= (path-length C-CS1 INPUT C-RS2 OUTPUT) 58.4958)
	 (= (path-length C-CS1 INPUT START INPUT) 53.621)
	 (= (path-length C-CS1 OUTPUT C-BS INPUT) 63.8106)
	 (= (path-length C-CS1 OUTPUT C-BS OUTPUT) 69.1358)
	 (= (path-length C-CS1 OUTPUT C-CS1 INPUT) 12.9856)
	 (= (path-length C-CS1 OUTPUT C-CS2 INPUT) 21.0577)
	 (= (path-length C-CS1 OUTPUT C-CS2 OUTPUT) 29.0468)
	 (= (path-length C-CS1 OUTPUT C-DS INPUT) 36.2971)
	 (= (path-length C-CS1 OUTPUT C-DS OUTPUT) 44.5635)
	 (= (path-length C-CS1 OUTPUT C-RS1 INPUT) 48.9831)
	 (= (path-length C-CS1 OUTPUT C-RS1 OUTPUT) 39.3569)
	 (= (path-length C-CS1 OUTPUT C-RS2 INPUT) 55.2177)
	 (= (path-length C-CS1 OUTPUT C-RS2 OUTPUT) 66.6277)
	 (= (path-length C-CS1 OUTPUT START INPUT) 61.1939)
	 (= (path-length C-CS2 INPUT C-BS INPUT) 50.0478)
	 (= (path-length C-CS2 INPUT C-BS OUTPUT) 55.373)
	 (= (path-length C-CS2 INPUT C-CS1 INPUT) 21.4872)
	 (= (path-length C-CS2 INPUT C-CS1 OUTPUT) 21.0577)
	 (= (path-length C-CS2 INPUT C-CS2 OUTPUT) 23.8494)
	 (= (path-length C-CS2 INPUT C-DS INPUT) 32.989)
	 (= (path-length C-CS2 INPUT C-DS OUTPUT) 41.2555)
	 (= (path-length C-CS2 INPUT C-RS1 INPUT) 35.2204)
	 (= (path-length C-CS2 INPUT C-RS1 OUTPUT) 35.3078)
	 (= (path-length C-CS2 INPUT C-RS2 INPUT) 51.1685)
	 (= (path-length C-CS2 INPUT C-RS2 OUTPUT) 59.6831)
	 (= (path-length C-CS2 INPUT START INPUT) 47.4312)
	 (= (path-length C-CS2 OUTPUT C-BS INPUT) 39.3321)
	 (= (path-length C-CS2 OUTPUT C-BS OUTPUT) 44.6572)
	 (= (path-length C-CS2 OUTPUT C-CS1 INPUT) 20.915)
	 (= (path-length C-CS2 OUTPUT C-CS1 OUTPUT) 29.0468)
	 (= (path-length C-CS2 OUTPUT C-CS2 INPUT) 23.8494)
	 (= (path-length C-CS2 OUTPUT C-DS INPUT) 25.2384)
	 (= (path-length C-CS2 OUTPUT C-DS OUTPUT) 37.7419)
	 (= (path-length C-CS2 OUTPUT C-RS1 INPUT) 24.5046)
	 (= (path-length C-CS2 OUTPUT C-RS1 OUTPUT) 25.8839)
	 (= (path-length C-CS2 OUTPUT C-RS2 INPUT) 41.7447)
	 (= (path-length C-CS2 OUTPUT C-RS2 OUTPUT) 48.9673)
	 (= (path-length C-CS2 OUTPUT START INPUT) 36.7154)
	 (= (path-length C-DS INPUT C-BS INPUT) 39.1852)
	 (= (path-length C-DS INPUT C-BS OUTPUT) 44.5104)
	 (= (path-length C-DS INPUT C-CS1 INPUT) 26.9309)
	 (= (path-length C-DS INPUT C-CS1 OUTPUT) 36.2971)
	 (= (path-length C-DS INPUT C-CS2 INPUT) 32.989)
	 (= (path-length C-DS INPUT C-CS2 OUTPUT) 25.2384)
	 (= (path-length C-DS INPUT C-DS OUTPUT) 14.639)
	 (= (path-length C-DS INPUT C-RS1 INPUT) 25.4461)
	 (= (path-length C-DS INPUT C-RS1 OUTPUT) 14.1725)
	 (= (path-length C-DS INPUT C-RS2 INPUT) 29.2344)
	 (= (path-length C-DS INPUT C-RS2 OUTPUT) 40.6444)
	 (= (path-length C-DS INPUT START INPUT) 36.5685)
	 (= (path-length C-DS OUTPUT C-BS INPUT) 27.5249)
	 (= (path-length C-DS OUTPUT C-BS OUTPUT) 34.9196)
	 (= (path-length C-DS OUTPUT C-CS1 INPUT) 35.1973)
	 (= (path-length C-DS OUTPUT C-CS1 OUTPUT) 44.5635)
	 (= (path-length C-DS OUTPUT C-CS2 INPUT) 41.2555)
	 (= (path-length C-DS OUTPUT C-CS2 OUTPUT) 37.7419)
	 (= (path-length C-DS OUTPUT C-DS INPUT) 14.639)
	 (= (path-length C-DS OUTPUT C-RS1 INPUT) 32.2671)
	 (= (path-length C-DS OUTPUT C-RS1 OUTPUT) 20.9667)
	 (= (path-length C-DS OUTPUT C-RS2 INPUT) 17.2738)
	 (= (path-length C-DS OUTPUT C-RS2 OUTPUT) 28.6838)
	 (= (path-length C-DS OUTPUT START INPUT) 32.4234)
	 (= (path-length C-RS1 INPUT C-BS INPUT) 19.127)
	 (= (path-length C-RS1 INPUT C-BS OUTPUT) 24.4522)
	 (= (path-length C-RS1 INPUT C-CS1 INPUT) 41.8211)
	 (= (path-length C-RS1 INPUT C-CS1 OUTPUT) 48.9831)
	 (= (path-length C-RS1 INPUT C-CS2 INPUT) 35.2204)
	 (= (path-length C-RS1 INPUT C-CS2 OUTPUT) 24.5046)
	 (= (path-length C-RS1 INPUT C-DS INPUT) 25.4461)
	 (= (path-length C-RS1 INPUT C-DS OUTPUT) 32.2671)
	 (= (path-length C-RS1 INPUT C-RS1 OUTPUT) 26.0916)
	 (= (path-length C-RS1 INPUT C-RS2 INPUT) 32.1897)
	 (= (path-length C-RS1 INPUT C-RS2 OUTPUT) 28.7623)
	 (= (path-length C-RS1 INPUT START INPUT) 16.5103)
	 (= (path-length C-RS1 OUTPUT C-BS INPUT) 30.0413)
	 (= (path-length C-RS1 OUTPUT C-BS OUTPUT) 35.3664)
	 (= (path-length C-RS1 OUTPUT C-CS1 INPUT) 31.225)
	 (= (path-length C-RS1 OUTPUT C-CS1 OUTPUT) 39.3569)
	 (= (path-length C-RS1 OUTPUT C-CS2 INPUT) 35.3077)
	 (= (path-length C-RS1 OUTPUT C-CS2 OUTPUT) 25.8839)
	 (= (path-length C-RS1 OUTPUT C-DS INPUT) 14.1725)
	 (= (path-length C-RS1 OUTPUT C-DS OUTPUT) 20.9667)
	 (= (path-length C-RS1 OUTPUT C-RS1 INPUT) 26.0916)
	 (= (path-length C-RS1 OUTPUT C-RS2 INPUT) 20.8894)
	 (= (path-length C-RS1 OUTPUT C-RS2 OUTPUT) 32.2994)
	 (= (path-length C-RS1 OUTPUT START INPUT) 27.4246)
	 (= (path-length C-RS2 INPUT C-BS INPUT) 21.2672)
	 (= (path-length C-RS2 INPUT C-BS OUTPUT) 28.662)
	 (= (path-length C-RS2 INPUT C-CS1 INPUT) 47.0858)
	 (= (path-length C-RS2 INPUT C-CS1 OUTPUT) 55.2177)
	 (= (path-length C-RS2 INPUT C-CS2 INPUT) 51.1685)
	 (= (path-length C-RS2 INPUT C-CS2 OUTPUT) 41.7447)
	 (= (path-length C-RS2 INPUT C-DS INPUT) 29.2344)
	 (= (path-length C-RS2 INPUT C-DS OUTPUT) 17.2738)
	 (= (path-length C-RS2 INPUT C-RS1 INPUT) 32.1897)
	 (= (path-length C-RS2 INPUT C-RS1 OUTPUT) 20.8894)
	 (= (path-length C-RS2 INPUT C-RS2 OUTPUT) 14.2613)
	 (= (path-length C-RS2 INPUT START INPUT) 26.6464)
	 (= (path-length C-RS2 OUTPUT C-BS INPUT) 11.5575)
	 (= (path-length C-RS2 OUTPUT C-BS OUTPUT) 15.5836)
	 (= (path-length C-RS2 OUTPUT C-CS1 INPUT) 58.4958)
	 (= (path-length C-RS2 OUTPUT C-CS1 OUTPUT) 66.6277)
	 (= (path-length C-RS2 OUTPUT C-CS2 INPUT) 59.6831)
	 (= (path-length C-RS2 OUTPUT C-CS2 OUTPUT) 48.9673)
	 (= (path-length C-RS2 OUTPUT C-DS INPUT) 40.6444)
	 (= (path-length C-RS2 OUTPUT C-DS OUTPUT) 28.6838)
	 (= (path-length C-RS2 OUTPUT C-RS1 INPUT) 28.7623)
	 (= (path-length C-RS2 OUTPUT C-RS1 OUTPUT) 32.2994)
	 (= (path-length C-RS2 OUTPUT C-RS2 INPUT) 14.2613)
	 (= (path-length C-RS2 OUTPUT START INPUT) 16.9367)
	 (= (path-length START INPUT C-BS INPUT) 7.3014)
	 (= (path-length START INPUT C-BS OUTPUT) 12.2342)
	 (= (path-length START INPUT C-CS1 INPUT) 53.621)
	 (= (path-length START INPUT C-CS1 OUTPUT) 61.1939)
	 (= (path-length START INPUT C-CS2 INPUT) 47.4312)
	 (= (path-length START INPUT C-CS2 OUTPUT) 36.7154)
	 (= (path-length START INPUT C-DS INPUT) 36.5685)
	 (= (path-length START INPUT C-DS OUTPUT) 32.4234)
	 (= (path-length START INPUT C-RS1 INPUT) 16.5103)
	 (= (path-length START INPUT C-RS1 OUTPUT) 27.4246)
	 (= (path-length START INPUT C-RS2 INPUT) 26.6464)
	 (= (path-length START INPUT C-RS2 OUTPUT) 16.9367)

	)

	(:goal (order-fulfilled o1))
)
